feat: add fonts-raleway
deepin-community/fonts-raleway pull request #1
Opened 2023-07-06 06:29 UTC by Udacv

Raleway is an elegant sans-serif typeface family.

Log: add fonts-raleway
Issue: deepin-community/sig-deepin-sysdev-team#168

2023-07-06 06:48 UTC, xzl01 requested changes
1. 缺少install文件，不知道自己安装到哪里
2. unstable的应该不打入包中

2023-07-06 07:54 UTC, Udacv commented
> 1. 缺少install文件，不知道自己安装到哪里
> 2. unstable的应该不打入包中

已修改，请龙哥再帮看看。

2023-07-06 08:12 UTC, Udacv commented
@xzl01

2023-07-07 05:24 UTC, Udacv commented
@chenchongbiao

2023-07-10 07:57 UTC, Udacv commented
@chenchongbiao 请学长查看

2023-07-11 08:06 UTC, xzl01 approved these changes

2023-07-11 08:07 UTC, merged